# Generated by Django 5.2.13 on 2026-04-24 17:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EngineMetaData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine_name', models.CharField(max_length=128, unique=True)),
                ('model_number', models.CharField(blank=True, max_length=64, null=True)),
                ('rated_power_kw', models.FloatField(blank=True, null=True)),
                ('rated_rpm', models.IntegerField(blank=True, null=True)),
                ('cylinders', models.IntegerField(blank=True, null=True)),
                ('fuel_type', models.CharField(blank=True, max_length=64, null=True)),
                ('firing_order', models.CharField(blank=True, max_length=64, null=True)),
                ('bore_mm', models.FloatField(blank=True, null=True)),
                ('stroke_mm', models.FloatField(blank=True, null=True)),
                ('valve_overlap_deg', models.FloatField(blank=True, null=True)),
                ('intake_manifold_cs_area', models.FloatField(blank=True, null=True)),
                ('exhaust_manifold_cs_area', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('engine', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metadata', to='core.engine')),
            ],
        ),
        migrations.CreateModel(
            name='ProcessedFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('rpm', models.IntegerField()),
                ('lub_oil_pressure', models.FloatField(blank=True, null=True)),
                ('jacket_cw_outlet_temp', models.FloatField(blank=True, null=True)),
                ('lub_oil_flow', models.FloatField(blank=True, null=True)),
                ('cooling_water_flow', models.FloatField(blank=True, null=True)),
                ('boost_air_temp', models.FloatField(blank=True, null=True)),
                ('boost_air_pressure', models.FloatField(blank=True, null=True)),
                ('boost_air_flow_after_cooler', models.FloatField(blank=True, null=True)),
                ('bmep', models.FloatField(blank=True, null=True)),
                ('combustion_temp', models.FloatField(blank=True, null=True)),
                ('exhaust_temp_c1', models.FloatField(blank=True, null=True)),
                ('exhaust_temp_c2', models.FloatField(blank=True, null=True)),
                ('exhaust_temp_c3', models.FloatField(blank=True, null=True)),
                ('exhaust_temp_c4', models.FloatField(blank=True, null=True)),
                ('exhaust_temp_c5', models.FloatField(blank=True, null=True)),
                ('exhaust_temp_c6', models.FloatField(blank=True, null=True)),
                ('fuel_temp', models.FloatField(blank=True, null=True)),
                ('fuel_flow', models.FloatField(blank=True, null=True)),
                ('fuel_pressure', models.FloatField(blank=True, null=True)),
                ('fuel_pump_rack', models.FloatField(blank=True, null=True)),
                ('exhaust_manifold_pressure', models.FloatField(blank=True, null=True)),
                ('piston_force', models.FloatField(blank=True, null=True)),
                ('mechanical_efficiency', models.FloatField(blank=True, null=True)),
                ('indicated_power_kw', models.FloatField(blank=True, null=True)),
                ('volumetric_efficiency', models.FloatField(blank=True, null=True)),
                ('frictional_loss_kw', models.FloatField(blank=True, null=True)),
                ('afr', models.FloatField(blank=True, null=True)),
                ('governor_response_time_s', models.FloatField(blank=True, null=True)),
                ('piston_speed_mps', models.FloatField(blank=True, null=True)),
                ('bsfc_g_per_kwh', models.FloatField(blank=True, null=True)),
                ('thermal_efficiency', models.FloatField(blank=True, null=True)),
                ('raw_meta', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('engine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processed', to='processor.enginemetadata')),
            ],
        ),
        migrations.CreateModel(
            name='PCAFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pc1', models.FloatField(blank=True, null=True)),
                ('pc2', models.FloatField(blank=True, null=True)),
                ('pc3', models.FloatField(blank=True, null=True)),
                ('loadings', models.JSONField(blank=True, null=True)),
                ('explained_variance', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('features', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pca', to='processor.processedfeatures')),
            ],
        ),
        migrations.CreateModel(
            name='AlarmFlags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lub_oil_low', models.BooleanField(default=False)),
                ('jacket_cw_high', models.BooleanField(default=False)),
                ('overspeed', models.BooleanField(default=False)),
                ('high_exhaust_temp', models.BooleanField(default=False)),
                ('low_fuel_pressure', models.BooleanField(default=False)),
                ('acknowledged', models.BooleanField(default=False)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_by', models.CharField(blank=True, max_length=128, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('features', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alarms', to='processor.processedfeatures')),
            ],
        ),
        migrations.CreateModel(
            name='StatisticalFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('window_size', models.IntegerField(default=20)),
                ('rpm_mean', models.FloatField(blank=True, null=True)),
                ('rpm_std', models.FloatField(blank=True, null=True)),
                ('lub_oil_pressure_mean', models.FloatField(blank=True, null=True)),
                ('lub_oil_pressure_std', models.FloatField(blank=True, null=True)),
                ('boost_air_pressure_mean', models.FloatField(blank=True, null=True)),
                ('boost_air_pressure_std', models.FloatField(blank=True, null=True)),
                ('exhaust_temp_mean', models.FloatField(blank=True, null=True)),
                ('exhaust_temp_std', models.FloatField(blank=True, null=True)),
                ('fuel_flow_mean', models.FloatField(blank=True, null=True)),
                ('fuel_flow_std', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('features', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='processor.processedfeatures')),
            ],
        ),
    ]
