# Generated by Django 5.2.13 on 2026-04-24 17:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('address', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_company_admin', models.BooleanField(default=False)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.company')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vessel',
            fields=[
                ('vessel_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('imo_number', models.CharField(blank=True, max_length=64, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vessels', to='core.company')),
            ],
        ),
        migrations.CreateModel(
            name='Engine',
            fields=[
                ('engine_id', models.AutoField(primary_key=True, serialize=False)),
                ('serial_number', models.CharField(max_length=128, unique=True)),
                ('model_name', models.CharField(max_length=128)),
                ('engine_type', models.CharField(choices=[('ME', 'Main Engine'), ('AE', 'Auxiliary Generator')], max_length=2)),
                ('rated_rpm', models.IntegerField(blank=True, null=True)),
                ('rated_power', models.IntegerField(blank=True, null=True)),
                ('rated_frequency', models.IntegerField(blank=True, null=True)),
                ('vessel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engines', to='core.vessel')),
            ],
        ),
    ]
